name: MDS_Group37

channels:
  - conda-forge

platforms:
  - linux-aarch64
  - linux-64
  - osx-arm64
  - osx-64
  - win-64

dependencies:
  # core dependencies
  - python=3.11.*
  - conda-lock>=3.0.4
  - pandas
  - scikit-learn
  - altair
  - numpy
  
  # jupyter - modern stack
  - jupyterlab
  - ipykernel
  - notebook
  
  # other tools
  - pytest
  - requests
  - click

  - pip 
  - pip:
    - altair_ally>=0.1.1
    - ucimlrepo
    - "deepchecks[tabular]"
    - anywidget