.PHONY: all clean help setup cl env build run up stop test

# Define python interpreter
PYTHON = python

.DEFAULT_GOAL := help

# ----------------------------------------------------------------------------
# Analysis Pipeline Targets 
# ----------------------------------------------------------------------------

# Target: all
# Description: Generates both HTML and PDF reports
all: reports/breast_cancer_predictor_report.pdf reports/breast_cancer_predictor_report.html

# Target: Download Data
data/raw/breast_cancer_raw.csv: scripts/1_download_data.py
	$(PYTHON) scripts/1_download_data.py

# Target: Clean Data
# Note: This runs the cleaning script to generate processed datasets
data/processed/breast_cancer_cleaned.csv \
data/processed/clean_train.csv \
data/processed/clean_test.csv: scripts/2_clean_data.py data/raw/breast_cancer_raw.csv
	$(PYTHON) scripts/2_clean_data.py

# ----------------------------------------------------------------------------
# Sentinel Logic for EDA (Prevents running script multiple times)
# ----------------------------------------------------------------------------

# Define all outputs generated by EDA script
EDA_OUTPUTS = results/images/corr_chart.png \
              results/images/dist_chart.png \
              results/images/pair_chart.png

# The actual outputs depend on the sentinel file
$(EDA_OUTPUTS): results/.eda.done

# The sentinel file depends on the script and data
# Once script runs successfully, we 'touch' the sentinel to update timestamp
results/.eda.done: scripts/3_eda.py data/processed/clean_train.csv
	$(PYTHON) scripts/3_eda.py
	touch results/.eda.done

# ----------------------------------------------------------------------------
# Sentinel Logic for Modeling (Prevents running script multiple times)
# ----------------------------------------------------------------------------

# Define all outputs generated by Modeling script
MODEL_OUTPUTS = results/models/ct.pickle \
                results/images/svm_heatmap.png \
                results/images/con_mat_heatmap.png

# The actual outputs depend on the sentinel file
$(MODEL_OUTPUTS): results/.model.done

# The sentinel file depends on the script and data
results/.model.done: scripts/4_model.py data/processed/clean_train.csv data/processed/clean_test.csv
	$(PYTHON) scripts/4_model.py
	touch results/.model.done

# ----------------------------------------------------------------------------
# Report Generation
# ----------------------------------------------------------------------------

reports/breast_cancer_predictor_report.html: reports/breast_cancer_predictor_report.qmd \
                                              reports/references.bib \
                                              $(EDA_OUTPUTS) \
                                              $(MODEL_OUTPUTS)
	quarto render reports/breast_cancer_predictor_report.qmd --to html

reports/breast_cancer_predictor_report.pdf: reports/breast_cancer_predictor_report.qmd \
                                             reports/references.bib \
                                             $(EDA_OUTPUTS) \
                                             $(MODEL_OUTPUTS)
	quarto render reports/breast_cancer_predictor_report.qmd --to typst

# ----------------------------------------------------------------------------
# Cleanup
# ----------------------------------------------------------------------------

clean:
	rm -rf data/raw/*
	rm -f data/processed/*.csv
	rm -f results/models/*.pickle
	rm -f results/images/*.png
	rm -f reports/breast_cancer_predictor_report.html \
	      reports/breast_cancer_predictor_report.pdf
	rm -f results/.eda.done results/.model.done
	rm -rf test/log/
	find . -type d -name "__pycache__" -exec rm -rf {} +

# ----------------------------------------------------------------------------
# Environment & Utilities Targets 
# ----------------------------------------------------------------------------

help: ## Show this help message
	@echo "Available commands:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}'

setup: ## runs the targets: cl, env, build
	make cl
	make env
	make build

cl: ## create conda lock for multiple platforms
	conda-lock lock \
		--file environment.yml \
		-p linux-64 \
		-p linux-aarch64 \
		-p osx-64 \
		-p osx-arm64 \
		-p win-64

env: ## remove previous and create environment from lock file
	conda env remove -n dockerlock || true
	conda-lock install -n dockerlock conda-lock.yml

build: ## build the docker image from the Dockerfile
	docker build -t dockerlock --file Dockerfile .

run: ## alias for the up target
	make up

up: ## stop and start docker-compose services
	make stop
	docker-compose up -d

stop: ## stop docker-compose services
	docker-compose stop

test: ## Run unit tests with logging
	$(PYTHON) test/run_tests.py